-- Adicionar novas colunas para dados de glosas completos
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS regulacao_perito TEXT;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS valores_auditado DECIMAL(12,2) DEFAULT 0;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS saving_pecas DECIMAL(12,2) DEFAULT 0;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS saving_mo DECIMAL(12,2) DEFAULT 0;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS saving_real DECIMAL(12,2) DEFAULT 0;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS saving_potencial TEXT;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS descricao_glosa TEXT;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS tipo_veiculo TEXT;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS fabricante TEXT;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS municipio TEXT;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS uf TEXT;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS houve_ajuste TEXT;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS mes INTEGER;
ALTER TABLE laudos ADD COLUMN IF NOT EXISTS ano INTEGER;
